var userCenterView={init:function(){this.changeTrLenColor();this.hoverShowBlock();this.changePanel();this.shareBtnClick();this.delOrderPop();this.messDel();this.selectEvent();this.cancel_ticket_order();this.cancel_hotel_order();this.cancel_train_order();},changeTrLenColor:function(){$('.table_order tr:not(:has(th)):odd').addClass('odd');},hoverShowBlock:function(){var o=$("#add_apply");var con=$("#apply_box");o.bind("click",function(){con.slideDown();con.find("li").hover(function(){$(this).addClass("cur");},function(){$(this).removeClass("cur");})
userCenterView.closeParent($(".Close_Btn"));})},closeParent:function(obj){var o=obj;o.click(function(){$(this).parent().slideUp();})},changePanel:function(){if($("#changeBtnHot").length){var i=0;var $len=$("#change_con .main_part_item");var num=$len.length;$("#changeBtnHot").click(function(){i++;$len.eq(i%num).show().siblings().hide();})}},shareBtnClick:function(){$(".Share_btn").click(function(){layer.tips($("#share_box").html(),this,{guide:2,style:['background-color:#444b5e; color:#fff','#444b5e'],maxWidth:120,time:0,closeBtn:[0,true]});})},delOrderPop:function(){$(".Del_Order_btn").click(function(){var self=$(this);$.layer({type:1,title:'提示',btns:2,btn:['确定','取消'],area:['460px','250px'],page:{html:'<div class="del_pop_box"><span class="pop_tip_icon"></span><p class="p1">您确定要删除该订单吗？</p>'+'<p class="p2">删除后，您可以在订单回收站还原该订单，也可以做永久删除。</p></div>'},yes:function(){var block_div=self.parents(".Indep_Order").eq(0);if(block_div.length){block_div.remove();}
else{self.parents("tbody").eq(0).remove();}
layer.closeAll();}});});},cancel_ticket_order:function(){$(".cancel_ticket_order").live('click',function(){var orderId=parseInt($(this).attr('data-id'));$.layer({type:1,title:'取消门票',btns:2,btn:['确定','取消'],area:['460px','250px'],page:{html:'<div class="del_pop_box"><span class="pop_tip_icon"></span><p class="p1">您是否真的需要取消此次行程？</p></div>'},yes:function(){var url="/usercenter/userajax/cancelTicketOrder";$.post(url,{'orderId':orderId},function(data){if(data&&data.success&&data.data.success){alert("订单取消成功！");window.location.reload();}else{alert("系统忙，请稍后再试！");return false;}},'json');layer.closeAll();}});});},cancel_hotel_order:function(){$(".cancel_hotel_order").live('click',function(){var orderId=parseInt($(this).attr('data-id'));var confirmUrl='/usercenter/userajax/cancelConfirmHotelOrder?id='+orderId+'&step=1';$.get(confirmUrl,function(d){if(!d||!d.success){alert("系统忙或者订单在取消中，请稍后再试！");return false;}
var cancelDesc=d.data?(d.data+"\r\n如您已担保或付款，我们将在订单取消后3个工作日内为您解除预授权或退款，银行到账时间为7-15个工作日，请您注意查收。\r\n\r\n"):'';$.layer({type:1,title:'取消酒店',btns:2,btn:['确定','取消'],area:['480px','450px'],page:{html:'<div class="del_pop_box"><span class="pop_tip_icon"></span><p class="p2">'+cancelDesc+'<br /><br />您确定要取消订单吗？</p></div>'},yes:function(){var url="/usercenter/userajax/cancelConfirmHotelOrder";$.post(url,{'id':orderId,'step':2},function(json){if(json&&json.success){if(json.data.success){alert("订单取消成功！");window.location.reload();}else{alert(json.data.msg);window.location.reload();}}else{alert("系统忙，请稍后再试！");return false;}},'json');layer.closeAll();}});},'json');});},cancel_train_order:function(){$(".cancel_train_order").live('click',function(){var orderId=parseInt($(this).attr('data-id'));var orderStatus=$(this).attr('data-status');var confirmUrl='/usercenter/userajax/cancelTrainOrder';$.post(confirmUrl,{'id':orderId},function(d){if(!d||!d.success){alert("系统忙，请稍后再试！");return false;}
var cancelTitel=(d.data.loss)?'您确认要退票吗？<br />':'您确认要取消订单吗？<br />';var cancelDesc=d.data.msg;$.layer({type:1,title:'取消火车票',btns:2,btn:['确定','取消'],area:['480px','280px'],page:{html:'<div class="del_pop_box"><span class="pop_tip_icon"></span><p class="p1">'+cancelTitel+cancelDesc+'</p></div>'},yes:function(){var url="/usercenter/userajax/sendCancelTrainOrder";$.post(url,{'id':orderId},function(data){if(data&&data.success){if(orderStatus=='购票成功'){alert("退票请求已接收，退票结果稍后返回，请关注短信提醒及订单状态更新！");}else{alert(data.data.msg);}
window.location.reload();}else{alert(data.data.msg);return false;}},'json');layer.closeAll();}});},'json');});},messDel:function(){$("#messList tbody tr").hover(function(){$(this).find(".Mess_Close").css("visibility","visible");},function(){$(this).find(".Mess_Close").css("visibility","hidden");})
userCenterView.delParents();},delParents:function(){$(".Mess_Close").click(function(){$(this).parent().parent().remove();})},selectEvent:function(){$(".Select_Box_Js").hover(function(){$(this).addClass("open");$(this).find("ul").show();},function(){$(this).removeClass("open");$(this).find("ul").hide();})
$(".Select_Box_Js li").click(function(){var _self=$(this);var _text=_self.text();_self.parent().parent().find("p").text(_text);_self.parent().hide();})}}
var userScreenSize={init:function(){this.resizeScreen();},resizeScreen:function(){var index1200=$("#index1200");if(!userScreenSize.isBigThan1280()){index1200.removeClass("index1200").addClass("index1000");}else{index1200.removeClass("index1000").addClass("index1200");}
$(window).resize(function(){if(!userScreenSize.isBigThan1280()){if(!index1200.hasClass("index1000")){index1200.removeClass("index1200").addClass("index1000");}}else{if(!index1200.hasClass("index1200")){index1200.removeClass("index1000").addClass("index1200");}}});},isIE6:function(){if($.browser.msie&&$.browser.version==6){return true;}else{return false;}},isBigThan1280:function(){var w_wd=$(window).width();if(w_wd>=1280){return true;}else{return false;}}}
$(function(){userCenterView.init();userScreenSize.init();});